### PR TITLE
First milestone

### PR DESCRIPTION
**Pull request by Zappat0n**
- Set up the environment
- Add prop-types and big.js packages
- Create app skeleton
- Add hello message
- Add Eslint and Stylelint
- Create Heroku deployment

### CODE REVIEW

**Review by arslanbisharat — APPROVED** [review]
# Approved :clap:

Hello Developer, :wave:

Thank You for submitting this Pull Request. I am thrilled to announce that your project has met all the minimum requirements and now it is approved. :clap:

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

**Review by mikenath223 — COMMENTED** [review]
### Hello @Zappat0n  👋

- [ ] Please fix the issue raised in the last review. There has been no new commit.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by Zappat0n** [comment]
This is the first project in the React module. I do not have any requirements to install Redux and I do not even know how It works.
That requirement must be from another project.
Best regards.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @Zappat0n  👋

**You've done pretty well here, nice attention to the project details. 👌**

However, let's make a couple of changes.

- [ ] Kindly remove the unnecessary logo asset files under the `public` directory.

- Apologies for the mix-up with the previous reviewer. 🤝

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Review by arslanbisharat — APPROVED** [review]
# Approved :clap:

Hello Developer, :wave:

Thank You for submitting this Pull Request. I am thrilled to announce that your project has met all the minimum requirements and now it is approved. :clap:

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

**Pull request merged**
